### ISSUE TITLE
cache rules not working, always hitting default config

### ISSUE THREAD

**Issue by kumarunster** [rishabhkailey/Grafana-Query-Cache#41]
Hi

following cache rule file is specified:

```
default:
  enabled: true
  acceptable_time_delta_seconds: 1799
  acceptable_time_range_delta_seconds: 599
  acceptable_max_points_delta: 259
  id: default

#cache_rules: []
cache_rules:
  - panel_selector:
      datasource: influxdb
      panel: yield_overall
#        cacheable: "true"
    cache_config:
      enabled: true
      acceptable_time_delta_seconds: 1799
      acceptable_time_range_delta_seconds: 599
      acceptable_max_points_delta: 259
      id: influxdb

  - panel_selector:
      datasource: influxdb
      panel: power_realtime
    cache_config:
      enabled: false
      acceptable_time_delta_seconds: 0
      acceptable_time_range_delta_seconds: 0
      acceptable_max_points_delta: 0
      id: power_realtime

```

Query (influxdb) is specified as:

```
//datasource=influxdb; panel=power_realtime;
import "strings"
```

The cache configuration is ignored. Always the dafault is used. What I'm missing here? Any hint approciated.

<img width="597" alt="Image" src="https://github.com/user-attachments/assets/b40cbdc0-bc7b-458a-b9f1-6cf344f428d8" />
